erDiagram
    Direccion{
        int id_direccion PK
        varchar calle
        int numero
        varchar localidad  
    }
    Organizacion{
        int id_Organizacion PK
        varchar nombre
        varchar descripcion
        varchar telefono
        varchar email
    }
    TipoDocumento{
        int id_tipoDocumento PK
        varchar nombre
        varchar descripcion
    }
    TipoUsuario{
        int id_tipoUsuario PK
        varchar nombre
        varchar descripcion
    }
    Usuario{
        int id_usuario PK
        varchar nombre
        varchar apellido
        varchar nombreUsuario
        varchar contrasenia        
        varchar telefono
        varchar email
        varchar documento
        TipoDocumento tipoDocumento FK
        int id_direccion FK
        int id_tipoUsuario FK
    }
    Casa{
        int id_casa PK
        varchar nombre
        varchar descripcion
        int id_organizacion FK
        int id_direccion FK
    }
    DetalleCasaUsuario{
        int id_detalleCasaUsuario PK
        varchar descripcion
        date fechaIngreso
        int id_casa FK
        int id_usuario FK
    }
    UnidadMedida{
        int id_unidadMedida PK
        varchar nombre
        varchar descripcion
    }
    Stock{
        int id_stock PK
        int id_producto FK
        int cantidad
        int id_casa FK
    }
    CategoriaProducto{
        int id_categoriaProducto PK
        varchar nombre
        varchar descripcion
        int id_stock FK
    }
    Producto{
        int id_producto PK
        varchar nombre
        varchar descripcion
        int id_categoriaProducto PK
        int id_unidadMedida PK
    }
    Pedido{
        int id_pedido PK
        date fecha
        time hora
        int id_casa FK
        int id_usuario FK
    }
    DetallePedidoProducto{
        int id_detallePedidoProducto PK
        varchar descripcion
        int cantidad
        int id_pedido FK
        int id_producto FK
        int id_estadoProductoPedido FK
    }
    Oferta{
        int id_oferta PK
        date fecha
        time hora
        int id_usuario FK
        int id_casa FK
    }
    DetalleOfertaProducto{
        int id_detalleOfertaProducto PK
        varchar descripcion
        int cantidad
        int id_oferta FK
        int id_producto FK
        int id_estadoProductoOferta FK
    }
    EstadoPedidoProducto{
        int id_estadoPedidoProducto PK
        varchar nombre
        varchar descripcion
    }
    EstadoOfertaProducto{
        int id_estadoOfertaProducto PK
        varchar nombre
        varchar descripcion
    }
    Transporte{
        int id_transporte PK
        varchar marca
        varchar modelo
        varchar patente
        int kilometraje
        varchar estadoITV
        year anio
        int id_organizacion FK
    }

Organizacion ||--|{ Casa : "tiene"
Organizacion ||--|{ Transporte : "tiene"
Casa }|--|| Direccion : "tiene"
Casa ||--|{ Stock : "tiene"

TipoUsuario ||--|{ Usuario : "tiene"
Usuario ||--|{ Pedido : "tiene"
Usuario ||--|{ Oferta : "tiene"
Usuario }|--|| Direccion : "tiene"
TipoDocumento ||--|{ Usuario : "tiene"

Casa ||--|{ Pedido : "tiene"
Casa ||--|{ Oferta : "tiene"
Casa ||--|{ Stock : "tiene"

Casa ||--|{ DetalleCasaUsuario : "tiene"
Usuario ||--|{ DetalleCasaUsuario : "tiene"

Pedido ||--|{ DetallePedidoProducto : "tiene"
Oferta ||--|{ DetalleOfertaProducto : "tiene"
EstadoPedidoProducto ||--|{ DetallePedidoProducto : "tiene"
EstadoOfertaProducto ||--|{ DetalleOfertaProducto : "tiene"
Producto ||--|{ DetallePedidoProducto : "tiene"
Producto ||--|{ DetalleOfertaProducto : "tiene"

CategoriaProducto ||--|{ Producto : "tiene"
UnidadMedida ||--|{ Producto : "tiene"

Stock ||--|{ CategoriaProducto : "tiene"