classDiagram
    Organizacion --o Casa : 1..*
    Organizacion --o Vehiculo : 1..*
    Casa *-- Direccion : 1..*

    TipoUsuario --* Usuario : 1..*
    TipoDocumento --* Usuario : 1..*
    Usuario *-- Direccion : 1..*
    Usuario --* Pedido : 1..*
    Usuario --* Oferta : 1..*

    Casa --* Pedido : 1..*
    Casa --* Oferta : 1..*
    Casa --* Stock : 1..*

    Usuario --o DetalleCasaUsuario : 1..*
    Casa --o DetalleCasaUsuario : 1..*

    Producto --o DetalleStockProducto : 1..*
    Stock --o DetalleStockProducto : 1..*
    CategoriaProducto --* Producto : 1..*
    UnidadMedida --o Producto : 1..*

    Pedido --o DetallePedido : 1..*
    Producto --o DetallePedido : 1..*
    EstadoPedido --o DetallePedido : 1..*
    Oferta --o DetalleOferta : 1..*
    Producto --o DetalleOferta : 1..*
    EstadoOferta --o DetalleOferta : 1..*

    DetallePedido --o EntregaPedido : 1..*
    DetalleOferta --o EntregaOferta : 1..*
    EstadoEntrega --o EntregaPedido : 1..*
    EstadoEntrega --o EntregaOferta : 1..*
    Direccion --o EntregaPedido : 1..*
    Direccion --o EntregaOferta : 1..*

    class Direccion {
        - varchar calle
        - int numero
        - varchar localidad
        
        +setCalle()
        +setNumero()
        +setLocalidad()

        +getCalle()
        +getNumero()
        +getLocalidad()
    }
    class Organizacion {
        - varchar nombre
        - Direccion direccion
        - varchar telefono
        - varchar email

        +setNombre()
        +setDireccion()
        +setTelefono()
        +setEmail()

        +getNombre()
        +getDireccion()
        +getTelefono()
        +getEmail()
    }
    class TipoDocumento {
        - varchar nombre
        - varchar descripcion

        +setNombre()
        +setDescripcion()

        +getNombre()
        +getDescripcion()
    }
    class TipoUsuario {
        - varchar nombre
        - varchar descripcion

        +setNombre()
        +setDescripcion()

        +getNombre()
        +getDescripcion()
    }
    class Usuario {
        - varchar nombre
        - varchar apellido
        - varchar nombreUsuario
        - varchar contrasenia
        - varchar telefono
        - varchar email
        - date fechaUnion
        - varchar documento
        - TipoDocumento tipoDocumento
        - TipoUsuario tipoUsuario
        - Direccion direccion

        +setNombre()
        +setApellido()
        +setNombreUsuario()
        +setContrasenia()
        +setTelefono()
        +setEmail()
        +setDocumento()
        +setTipoDocumento()
        +setTipoUsuario()
        +setDireccion()

        +getNombre()
        +getApellido()
        +getNombreUsuario()
        +getContrasenia()
        +getTelefono()
        +getEmail()
        +getDocumento()
        +getTipoDocumento()
        +getTipoUsuario()
        +getDireccion()
    }
    class Casa {
        - varchar nombre
        - varchar descripcion
        - Organizacion organizacion
        - Direccion direccion

        +setNombre()
        +setDescripcion()
        +setOrganizacion()
        +setDireccion()

        +getNombre()
        +setDescripcion()
        +getOrganizacion()
        +getDireccion()
    }
    class DetalleCasaUsuario {      
        - varchar descripcion
        - date fechaIngreso
        - Casa casa
        - Usuario usuario

        +setDescripcion()
        +setFechaIngreso()
        +setCasa()
        +setUsuario()

        +getDescripcion()
        +getFechaIngreso()
        +getCasa()
        +getUsuario()
    }
    class UnidadMedida {
        - varchar nombre
        - varchar descripcion

        +setNombre()
        +setDescripcion()

        +getNombre()
        +getDescripcion()
    }
    class Stock {
        - Casa casa

        +setCantidad()

        +getCantidad()
    }
    class CategoriaProducto {
        - varchar nombre
        - varchar descripcion

        +setNombre()
        +setDescripcion()

        +getNombre()
        +getDescripcion()
    } 
    class Producto {
        - varchar nombre
        - varchar descripcion
        - CategoriaProducto categoriaProducto
        - UnidadMedida unidadMedida

        +setNombre()
        +setDescripcion()
        +setCategoriaProducto()
        +setUnidadMedida()

        +getNombre()
        +getDescripcion()
        +getCategoriaProducto()
        +getUnidadMedida()
    }
    class DetalleStockProducto {
        - Producto producto
        - Stock stock
        - int cantidad

        +setProducto()
        +setStock()
        +setCantidad()

        +getProducto()
        +getStock()
        +getCantidad()
    }
    class Pedido {
        - Casa casa
        - Usuario usuario
        - date fecha
        - time hora

        +setCasa()
        +setUsuario()
        +setFecha()
        +setHora()

        +getCasa()
        +getUsuario()
        +getFecha()
        +getHora()
    }
    class DetallePedido {
        - EstadoPedido estadoPedido
        - Pedido pedido
        - Producto producto
        - int cantidad
        - varchar descripcion

        +setEstadoPedido()
        +setPedido()
        +setProducto()
        +setCantidad()
        +setDescripcion()

        +getEstadoPedido()
        +getPedido()
        +getProducto()
        +getCantidad()
        +getDescripcion()
    }
    class EntregaPedido{
        - date fechaEntrega
        - time horaEntrega
        - DetallePedido detallePedido
        - EstadoEntrega estadoEntrega
        - Direccion direccion

        +setFechaEntrega()
        +setHoraEntrega()
        +setDetallePedido()
        +setEstadoEntrega()
        +setDireccion()

        +getFechaEntrega()
        +getHoraEntrega()
        +getDetallePedido()
        +getEstadoEntrega()
        +getDireccion()
    }
    class Oferta {
        - Casa casa
        - Usuario usuario
        - date fecha
        - time hora

        +setCasa()
        +setUsuario()
        +setFecha()
        +setHora()

        +getCasa()
        +getUsuario()
        +getFecha()
        +getHora()
    }
    class DetalleOferta {
        - EstadoOferta estadoOferta
        - Oferta oferta
        - Producto producto
        - int cantidad
        - varchar descripcion

        +setEstadoOferta()
        +setOferta()
        +setProducto()
        +setCantidad()
        +setDescripcion()

        +getEstadoOferta()
        +getOferta()
        +getProducto()
        +getCantidad()
        +getDescripcion()
    }
    class EntregaOferta{
        - date fechaEntrega
        - time horaEntrega
        - DetalleOferta detalleOferta
        - EstadoEntrega estadoEntrega
        - Direccion direccion

        +setFechaEntrega()
        +setHoraEntrega()
        +setDetalleOferta()
        +setEstadoEntrega()
        +setDireccion()

        +getFechaEntrega()
        +getHoraEntrega()
        +getDetalleOferta()
        +getEstadoEntrega()
        +getDireccion()
    }
    class EstadoPedido {
        - varchar nombre
        - varchar descripcion

        +setNombre()
        +setDescripcion()

        +getNombre()
        +getDescripcion()
    }
    class EstadoOferta {
        - varchar nombre
        - varchar descripcion

        +setNombre()
        +setDescripcion()

        +getNombre()
        +getDescripcion()
    }
    class EstadoEntrega {
        - varchar nombre
        - varchar descripcion

        +setNombre()
        +setDescripcion()

        +getNombre()
        +getDescripcion()
    }
    class Vehiculo {
        - varchar marca
        - varchar modelo
        - varchar patente
        - int kilometraje
        - varchar estadoITV
        - year anio
        - Organizacion organizacion

        +setMarca()
        +setModelo()
        +setPatente()
        +setKilometraje()
        +setEstadoITV()
        +setAnio()
        +setOrganizacion()

        +getMarca()
        +getModelo()
        +getPatente()
        +getKilometraje()
        +getEstadoITV()
        +getAnio()
        +getOrganizacion()
    }
