from django.urls import path
from ProntaEntregaApp.views import *

urlpatterns = [
    path('', view=index, name='index'),
    path('register/', UserRegister.as_view(), name='user_register'),
    path('login/', UserLogin.as_view(), name='user_login'),
    path('userToken/<str:token>', UserByToken.as_view(), name='userToken'),
    path('profile/', UserPage.as_view(), name='profile'),
    path('user/', VerUsuarios.as_view(), name='users'),
    path('user/<str:email>', UserByEmail.as_view(), name='userEmail'),
    path('cambiar_contrasenia/', CambiarContrasenia.as_view(), name='change_password'),
    path('CambiarProducto/<int:pk>/', CambiarProducto.as_view(), name='CambiarProducto'),
    path('CambiarDetalleStock/<int:pk>/', CambiarDetalleStock.as_view(), name='CambiarDetalleStock'),
    path('stock/<int:categoria_id>/', VerStockYProducto.as_view(), name='ver_stock_producto'),
    path('PostProducto/', PostProducto.as_view(), name='PostProducto'),
    path('PostDetallestockproducto/', PostDetallestockproducto.as_view(), name='PostDetallestockproducto'),
    path('tipo_documento/', verTipoDocumento.as_view(), name='ver_tipo_documento'),
    path('crear_casa/', CasaPost.as_view(), name='casa_post'),
    path('casa/', CasaGet.as_view(), name='casa_get'),
    path('editar_casa/<int:pk>', EditarCasa.as_view(), name='casa_edit'),
    path('direcciones/', GetDirecciones.as_view(), name='direcciones_get'),
    path('crear_direccion/', CrearDirecciones.as_view(), name='direcciones_post'),
    path('direccion/<int:pk>', GetDireccion.as_view(), name='direccion_get'),
    path('editar_direccion/<int:pk>/', EditarDirecciones.as_view(), name='direcciones_edit'),
    path('user/delete/<int:pk>/', UserDelete.as_view(), name='user_delete'),
    path('api/usuarios/update/<int:pk>/', UserUpdate.as_view(), name='user-update'),
    path('categoria/', Categoria.as_view(), name='categoria_producto'),
    path('categoria/delete/<int:pk>/', CategoriaDelete.as_view(), name='categoria_delete'),
    path('categoria/post', CategoriaPost.as_view(), name='categoria_post'),
]
