# Generated by Django 5.0.6 on 2024-08-22 13:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AporteOferta',
            fields=[
                ('id_aporteOferta', models.AutoField(db_column='id_aporteOferta', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AporteOferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AportePedido',
            fields=[
                ('id_aportePedido', models.AutoField(db_column='id_aportePedido', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'AportePedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(db_column='id_categoria', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CodigosDeVerificacion',
            fields=[
                ('codigos_id', models.AutoField(primary_key=True, serialize=False)),
                ('codigo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'codigos_de_verificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleobrapedido',
            fields=[
                ('id_detalleobrapedido', models.AutoField(db_column='id_DetalleObraPedido', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DetalleObraPedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleobratransporte',
            fields=[
                ('id_detalleobratransporte', models.AutoField(db_column='id_detalleObraTransporte', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DetalleObraTransporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleobrausuario',
            fields=[
                ('id_detalleobrausuario', models.AutoField(db_column='id_detalleObraUsuario', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaingreso', models.DateField(blank=True, db_column='fechaIngreso', null=True)),
            ],
            options={
                'db_table': 'DetalleObraUsuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detallestockproducto',
            fields=[
                ('id_detallestockproducto', models.AutoField(db_column='id_detalleStockProducto', primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(blank=True, null=True)),
                ('checkpoint', models.BooleanField(blank=True, default=False, null=True)),
                ('fecha_creacion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DetalleStockProducto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id_direccion', models.AutoField(primary_key=True, serialize=False)),
                ('localidad', models.CharField(blank=True, max_length=255, null=True)),
                ('numero', models.IntegerField(blank=True, null=True)),
                ('calle', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Direccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadooferta',
            fields=[
                ('id_estadoOferta', models.AutoField(db_column='id_estadoOferta', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EstadoOferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estadopedido',
            fields=[
                ('id_estadoPedido', models.AutoField(db_column='id_estadoPedido', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EstadoPedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('notificacion_id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('viewed', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notificacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id_obra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(upload_to='obras/')),
            ],
            options={
                'db_table': 'Obra',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oferta',
            fields=[
                ('id_oferta', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechavencimiento', models.DateField(blank=True, db_column='fechaVencimiento', null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Oferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Organizacion',
            fields=[
                ('id_organizacion', models.AutoField(db_column='id_Organizacion', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'Organizacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.AutoField(primary_key=True, serialize=False)),
                ('fechainicio', models.DateField(blank=True, db_column='fechaInicio', null=True)),
                ('fechavencimiento', models.DateField(blank=True, db_column='fechaVencimiento', null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
                ('urgente', models.IntegerField(blank=True, choices=[(1, 'No es urgente'), (2, 'Ligeramente Urgente'), (3, 'Muy Urgente'), (4, 'Inmediato')], null=True)),
            ],
            options={
                'db_table': 'Pedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('unidadmedida', models.IntegerField(blank=True, choices=[(0, 'Unidad/es'), (1, 'Kilogramo/s'), (2, 'Litro/s'), (3, 'Metro/s')], db_column='unidadMedida', null=True)),
                ('talle', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad_por_unidad', models.IntegerField(blank=True, null=True)),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('perecedero', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Producto',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id_stock', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Stock',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipodocumento',
            fields=[
                ('id_tipodocumento', models.AutoField(db_column='id_tipoDocumento', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TipoDocumento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tipousuario',
            fields=[
                ('id_tipousuario', models.AutoField(db_column='id_tipoUsuario', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('abreviacion', models.CharField(blank=True, max_length=20, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'TipoUsuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transporte',
            fields=[
                ('id_transporte', models.AutoField(primary_key=True, serialize=False)),
                ('marca', models.CharField(blank=True, max_length=255, null=True)),
                ('modelo', models.CharField(blank=True, max_length=255, null=True)),
                ('patente', models.CharField(blank=True, max_length=20, null=True)),
                ('kilometraje', models.IntegerField(blank=True, null=True)),
                ('estadoitv', models.CharField(blank=True, db_column='estadoITV', max_length=255, null=True)),
                ('anio', models.TextField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='vehiculos/')),
                ('necesita_mantenimiento', models.BooleanField(default=False)),
                ('descripcion_mantenimiento', models.CharField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'db_table': 'Transporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CustomUsuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('apellido', models.CharField(blank=True, max_length=255, null=True)),
                ('nombreusuario', models.CharField(blank=True, db_column='nombreUsuario', max_length=255, null=True, unique=True)),
                ('documento', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('genero', models.IntegerField(blank=True, choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Prefiero no decirlo')], null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='profilePictures/')),
                ('fechaUnion', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_login', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last login')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'CustomUsuario',
                'managed': False,
            },
        ),
    ]
