# Generated by Django 5.0.6 on 2024-07-30 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='aporteoferta',
            table='AporteOferta',
        ),
        migrations.AlterModelTable(
            name='aportepedido',
            table='AportePedido',
        ),
    ]
