# Generated by Django 5.0.6 on 2024-09-24 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id_entrega', models.AutoField(primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateField(blank=True, db_column='fechaCreacion', null=True)),
            ],
            options={
                'db_table': 'Entrega',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EntregaAporte',
            fields=[
                ('id_entregaAporte', models.AutoField(db_column='id_entregaAporte', primary_key=True, serialize=False)),
                ('fechaCreacion', models.DateField(blank=True, db_column='fechaCreacion', null=True)),
                ('fechaEntrega', models.DateField(blank=True, db_column='fechaEntrega', null=True)),
            ],
            options={
                'db_table': 'EntregaAporte',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EstadoEntrega',
            fields=[
                ('id_estadoEntrega', models.AutoField(db_column='id_estadoEntrega', primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'EstadoEntrega',
                'managed': False,
            },
        ),
    ]
