# Generated by Django 5.0.6 on 2024-08-06 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalleobrapedido',
            fields=[
                ('id_detalleobrapedido', models.AutoField(db_column='id_DetalleObraPedido', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DetalleObraPedido',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Detalleobrausuario',
            fields=[
                ('id_detalleobrausuario', models.AutoField(db_column='id_detalleObraUsuario', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('fechaingreso', models.DateField(blank=True, db_column='fechaIngreso', null=True)),
            ],
            options={
                'db_table': 'DetalleObraUsuario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Obra',
            fields=[
                ('id_obra', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('imagen', models.ImageField(upload_to='obras/')),
            ],
            options={
                'db_table': 'Obra',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Casa',
        ),
        migrations.DeleteModel(
            name='Detallecasausuario',
        ),
    ]
