# Generated by Django 5.0.6 on 2024-06-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0002_customusuario_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(1, 'Hombre'), (2, 'Mujer'), (3, 'Prefiero no decirlo')], null=True),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='profilePictures/'),
        ),
    ]
