# Generated by Django 5.0.6 on 2024-08-23 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0002_detallecategoriatags_tags'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Detallecategoriatags',
        ),
        migrations.DeleteModel(
            name='Tags',
        ),
    ]
