# Generated by Django 5.0.6 on 2024-08-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0002_detalleobrapedido_detalleobrausuario_obra_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleObraTransporte',
            fields=[
                ('id_detalleObraTransporte', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'DetalleObraTransporte',
                'managed': False,
            },
        ),
    ]
