# Generated by Django 5.0.6 on 2024-05-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0002_detalleoferta_detallepedido_detallestockproducto_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={},
        ),
    ]
