# Generated by Django 5.0.6 on 2024-07-30 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0002_notificacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='AporteOferta',
            fields=[
                ('id_aporteOferta', models.AutoField(db_column='id_detalleOferta', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DetalleOferta',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AportePedido',
            fields=[
                ('id_aportePedido', models.AutoField(db_column='id_detallePedido', primary_key=True, serialize=False)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('cantidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'DetallePedido',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='Detalleoferta',
        ),
        migrations.DeleteModel(
            name='Detallepedido',
        ),
    ]
