# Generated by Django 5.0.6 on 2024-08-13 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0003_detalleobratransporte'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoriaproducto',
        ),
        migrations.DeleteModel(
            name='Unidadmedida',
        ),
    ]
