# Generated by Django 5.0.6 on 2024-05-26 13:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0003_alter_usuario_options'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='dni',
        ),
        migrations.AddField(
            model_name='usuario',
            name='documento',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fechaUnion',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='usuario',
            name='genero',
            field=models.IntegerField(blank=True, choices=[(0, 'Hombre'), (1, 'Mujer'), (2, 'Prefiero no decirlo')], null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_direccion',
            field=models.ForeignKey(blank=True, db_column='id_direccion', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProntaEntregaApp.direccion'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_tipodocumento',
            field=models.ForeignKey(blank=True, db_column='id_tipoDocumento', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProntaEntregaApp.tipodocumento'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='id_tipousuario',
            field=models.ForeignKey(blank=True, db_column='id_tipoUsuario', null=True, on_delete=django.db.models.deletion.SET_NULL, to='ProntaEntregaApp.tipousuario'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='nombreusuario',
            field=models.CharField(blank=True, db_column='nombreUsuario', max_length=255, null=True, unique=True),
        ),
    ]
