# Generated by Django 5.0.6 on 2024-08-20 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0004_delete_categoriaproducto_delete_unidadmedida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transporte',
            options={'managed': True},
        ),
    ]
