# Generated by Django 5.0.6 on 2024-05-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0005_remove_usuario_contrasenia_usuario_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='contrasenia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
