# Generated by Django 5.0.6 on 2024-06-03 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0009_usuario_is_staff'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': True},
        ),
    ]
