# Generated by Django 5.0.6 on 2024-06-03 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProntaEntregaApp', '0010_alter_usuario_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
